[tox]
min_version = 4.0
isolated_build = true
env_list =
    py{39,310,311,312,313}
    check
    clean

[gh-actions]
python =
    3.9: py39
    3.10: py310
    3.11: py311
    3.12: py312, check
    3.13: py313

[testenv]
setenv =
    PYTHONPATH={toxinidir}/tests
    PYTHONUNBUFFERED=yes
passenv =
    *
deps =
    pytest
    pytest-cov
    setuptools_scm
    coverage
commands =
    pytest --cov=mlx --cov-report=term-missing -vv tests/
    submodule-guardian -h
    submodule-guardian --version

[testenv:check]
description = Run static analysis and packaging checks.
skip_install = true
deps =
    flake8
    check-manifest
    twine
    build
commands =
    flake8 src/ tests/
    check-manifest {toxinidir} -u
    python -m build
    twine check dist/*

[testenv:coverage]
deps = coverage
skip_install = true
commands =
    coverage xml --ignore-errors

[testenv:report]
deps = coverage
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
commands = coverage erase
skip_install = true
deps = coverage

[flake8]
max-line-length = 120
exclude = .git, build, dist, .tox
